server:
  port: 1016

program-agent:
  charts:
    bot-message: true
  client:
    token: "tuts-token-dew-bot"
    time-delay-send: 15000
    host: "https://wds-program-agent.ru/api/"
    myHost: "http://localhost:1016/api/"

telegram:
  bot:
    username: "MyTestBotanBot"
    token: "6488103958:AAHPKFMMzIODMGILBUp0-mLOcYj6Ybfocik"
    session:
      enable: true
      time-life:
        chat: 60
        user: 10

bot:
  data_base: testbot


spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${bot.data_base}
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: ru.wdeath.programagent.lib.config.WDSDBDialect
    open-in-view: false
    show-sql: true

